---
name: Push on main branch

concurrency:
  group: main-push-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/main/**"
      - "src/test/**"
      - "pom.xml"

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: 🧹 Clean and Compile
        run: $MVN clean compile

      - name: 🧪 Run Tests
        run: $MVN test --batch-mode --fail-at-end

      - name: 📡 SonarCloud Scan
        run: $MVN verify sonar:sonar -Dsonar.organization=magnus-ullberg -Dsonar.projectKey=magnus-ullberg_startpunkt -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}