---
name: Push on main branch

concurrency:
  group: main-push-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/main/**"
      - "src/test/**"
      - "pom.xml"

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📡 SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=magnus-ullberg
            -Dsonar.projectKey=magnus-ullberg_startpunkt